name: Setup project
description: Generate GitHub token, configure GIT, install pnpm, setup Node, install dependencies

inputs:
  client-id:
    description: GitHub App client ID
    required: true
  private-key:
    description: GitHub App private key
    required: true
  permission-contents:
    description: Contents permission for the GitHub App token
    required: false
  permission-pull-requests:
    description: Pull requests permission for the GitHub App token
    required: false
  install:
    description: Should install dependencies
    required: true
    default: "false"

outputs:
  token:
    description: GitHub App installation access token
    value: ${{ steps.generate-github-token.outputs.token }}
  app-slug:
    description: GitHub App slug
    value: ${{ steps.generate-github-token.outputs.app-slug }}

runs:
  using: composite
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
      with:
        cache: true
        install: ${{ inputs.install }}

    - name: Setup Node.js (CI)
      id: setup-node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: package.json

    - name: Generate GitHub token
      id: generate-github-token
      uses: ./.github/actions/generate-token
      with:
        client-id: ${{ inputs.client-id }}
        private-key: ${{ inputs.private-key }}
        permission-contents: ${{ inputs.permission-contents }}
        permission-pull-requests: ${{ inputs.permission-pull-requests }}

    - shell: bash
      run: pnpm i @actions/core @actions/github --filter=@root/github

    - name: Configure Git Identity
      id: configure-git-identity
      uses: ./.github/actions/configure-git-identity
      with:
        token: ${{ steps.generate-github-token.outputs.token }}
        app-slug: ${{ steps.generate-github-token.outputs.app-slug }}
