name: Setup project
description: Checkout, install pnpm, setup Node, install dependencies

inputs:
  client-id:
    description: GitHub App client ID
    required: true
  private-key:
    description: GitHub App private key
    required: true

outputs:
  token:
    description: GitHub App installation access token
    value: ${{ steps.generate-token.outputs.token }}
  app-slug:
    description: GitHub App slug
    value: ${{ steps.generate-token.outputs.app-slug }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Generate GitHub token
      id: generate-token
      uses: ./.github/actions/generate-token
      with:
        client-id: ${{ inputs.client-id }}
        private-key: ${{ inputs.private-key }}

    - name: Configure Git Identity
      shell: bash
      run: .github/scripts/configure-git-identity.sh
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ steps.generate-token.outputs.token }}
        APP_SLUG: ${{ steps.generate-token.outputs.app-slug }}

    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        cache: true
        # --frozen-lockfile might be redundant as for ci environments it's always set
        # https://pnpm.io/cli/install#--frozen-lockfile
        run_install: |
          args: [--frozen-lockfile]

    - name: Setup node
      uses: ./.github/actions/setup-node