name: Setup project
description: Generate GitHub token, configure GIT, install pnpm, setup Node, install dependencies

inputs:
  app-id:
    description: GitHub App ID
    required: true
  private-key:
    description: GitHub App private key
    required: true
  permission-pull-requests:
    description: The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges. Can be set to 'read' or 'write'.
  permission-contents:
    description: The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges. Can be set to 'read' or 'write'.
  install:
    description: Should install dependencies
    required: true
    default: "false"

outputs:
  token:
    description: GitHub App installation access token
    value: ${{ steps.create-github-token.outputs.token }}
  app-slug:
    description: GitHub App slug
    value: ${{ steps.create-github-token.outputs.app-slug }}

runs:
  using: composite
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
      with:
        cache: true
        install: ${{ inputs.install }}

    - name: Create GitHub token
      id: create-github-token
      uses: ./.github/actions/create-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        permission-contents: ${{ inputs.permission-contents }}
        permission-pull-requests: ${{ inputs.permission-pull-requests }}
