packages:
  - .github
  - packages/*
  - apps/*

hoist: false
saveExact: true
cleanupUnusedCatalogs: true

versioning:
  changelog:
    storage: repository

catalogs:
  types:
    "@types/node": 26.5.1
    "@pnpm/types": 1102.1.0
    "@octokit/webhooks-types": 7.6.1
    "@octokit/types": 18.0.0
    "@types/http-proxy": 1.17.17
    "@verdaccio/types": 13.0.6
    type-fest: 5.9.0
    better-typescript: 0.2.4
  test:
    vitest: 5.0.0
  dev:
    vite: 8.3.0
    typescript: 7.0.2
    actions-up: 1.20.0
    turbo: 2.10.13
    clean-publish: 7.1.0
    tsdown: 0.23.0
    postcss: 8.5.28
    commitizen: 4.3.2
    cz-conventional-changelog: 3.3.0
    "@commitlint/cli": 21.2.2
    "@commitlint/cz-commitlint": 21.2.2
    oxfmt: 0.68.0
    http-proxy: 1.18.1
    msw: 2.15.0
    "@mswjs/http-middleware": 0.10.3
  actions:
    "@actions/core": 3.0.1
    "@actions/github": 9.1.1
    "@octokit/auth-app": 8.3.1
    "@actions/exec": 3.0.0
    "@octokit/plugin-rest-endpoint-methods": 18.0.0
    verdaccio: 6.10.3
    verdaccio-memory: 10.5.3
  lint:
    oxlint: 1.83.0
    eslint: 10.10.0
    eslint-plugin-no-only-tests: 3.4.0
    eslint-plugin-perfectionist: 5.11.0
    eslint-plugin-react-hooks: 7.1.1
    eslint-plugin-unused-imports: 4.4.1
    yaml-eslint-parser: 2.1.0
    eslint-plugin-github-action: 0.4.0

allowBuilds:
  msw: true
  node: true
