packages:
  - .github
  - .changeset
  - packages/*
  - apps/*

hoist: false

versioning:
  changelog:
    storage: repository

catalogs:
  types:
    "@types/node": 26.1.2
    "@changesets/types": 6.1.0
    "@commitlint/types": 21.2.0
  dev:
    vite: 8.1.5
    vitest: 4.1.10
    typescript: 7.0.2
    actions-up: 1.16.0
    turbo: 2.10.7
    "@changesets/cli": 3.0.0-next.6
    "@pshevche/act-test-runner": 1.1.0
    clean-publish: 7.1.0
    tsdown: 0.22.14
    postcss: 8.x.x
    lefthook: 2.1.10
    oxfmt: 0.60.0
    oxlint: 1.75.0
    commitizen: 4.3.2
    cz-conventional-changelog: 3.3.0
    "@commitlint/cli": 21.2.1
    "@commitlint/cz-commitlint": 21.2.0
    "@commitlint/config-conventional": 21.2.0

allowBuilds:
  lefthook: false
  msw: true

patchedDependencies:
  '@pshevche/act-test-runner': patches/@pshevche__act-test-runner.patch
