name: Create release PR
description: Version packages and create release PR

runs:
  using: composite
  steps:
    - name: Version packages
      shell: bash
      run: .github/scripts/index.ts

    - name: Create/update release PR
      shell: bash
      run: .github/scripts/create-update-release-pr.sh
      env:
        RELEASE_BRANCH_NAME: ${{ vars.RELEASE_BRANCH_NAME }}
