name: Guard Release PR
description: GitHub Action that prevents manual creation of release PRs

inputs:
  token:
    description: GitHub installation access token
    required: true
  release-branch-name:
    description: Branch that contains all the changes needed for the release
    required: true

runs:
  using: node24
  main: index.ts
