name: Add pending change files
description: GitHub Action for generating pending change files used for testing

inputs:
  branch-name:
    description: Branch to commit generated change files to
    required: true
  change-file-summary:
    description: Generated change file summary
    required: true

runs:
  using: node24
  main: index.ts
