name: GitHub token
description: Generates GitHub App installation access token

inputs:
  client-id:
    description: GitHub App client ID
    required: true
  private-key:
    description: GitHub App private key
    required: true

outputs:
  token:
    description: GitHub App installation access token
    value: ${{ steps.generate-token-ci.outputs.token || steps.generate-token-act.outputs.token }}
  app-slug:
    description: GitHub App slug
    value: ${{ steps.generate-token-ci.outputs.app-slug || steps.generate-token-act.outputs.app-slug }}

runs:
  using: composite
  steps:
    - name: Generate GitHub token (CI)
      # actions/create-github-app-token is not supported by Act at the moment
      if: env.ACT != 'true'
      id: generate-token-ci
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        client-id: ${{ inputs.client-id }}
        private-key: ${{ inputs.private-key }}

    - name: Generate GitHub token (ACT)
      if: env.ACT == 'true'
      id: generate-token-act
      shell: bash
      run: |
        echo "token=some-token" >> "$GITHUB_OUTPUT"
        echo "app-slug=some-app-slug" >> "$GITHUB_OUTPUT"
