name: Setup pnpm
description: Sets up pnpm using aggressive caching

inputs:
  install:
    description: Should install packages
    required: true
    default: "false"

runs:
  using: composite
  steps:


    - name: Install dependencies
      id: install-dependencies
      if: inputs.install == 'true'
      shell: bash
      # --frozen-lockfile might be redundant as for ci environments it's always set
      # https://pnpm.io/cli/install#--frozen-lockfile
      run: pnpm install --frozen-lockfile
