name: Bump versions and update changelogs
description: GitHub Action for bumping versions and updating changelogs based on existing change files

inputs:
  release-branch-name:
    description: Branch to commit updated package.json and changelog files to
    required: true
  private-registry-url:
    description: Registry to publish private packages to
    required: true

outputs:
  status:
    description: Information about updated packages

runs:
  using: node24
  main: index.ts
