name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # for trusted publishing
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: pnpm ci

      - name: Build
        run: pnpm build

      - name: Publish plan
        uses: changesets/action/pack@v2.0.0-next.3 # v1.9.0
