name: GitHub Workflow to prevent manual creation of the release PR

permissions: {}

on:
  pull_request:
    branches:
      - main

jobs:
  guard-against-manual-pr-creation:
    environment: release
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == vars.RELEASE_BRANCH_NAME
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          persist-credentials: false

      - uses: ./.github/actions/setup
        id: setup
        with:
          app-id: ${{ vars.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
          permission-contents: read
          permission-pull-requests: write
          install: true

      - uses: ./.github/actions/guard-release-pr
        with:
          token: ${{ steps.setup.outputs.token }}
          release-branch-name: ${{ vars.RELEASE_BRANCH_NAME  }}
