name: PR check

env:
  # errexit - exit immediately if any command fails
  # nounset - error on use of undefined variables
  # pipefail - pipeline fails if any command in it fails, not just the last one
  SHELLOPTS: errexit:nounset:pipefail

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Lint, test, and check changes
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Configure local repository fallback (only for tests)
        if: env.ACT == 'true'
        run: |
          git config --global url."file:///host-repo/".insteadOf "https://github.com/smashercosmo/postcss-responsive-hints"

      - name: Checkout repository
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # DUMMY_GITHUB_TOKEN (any string that doesn't start with `ghs_`)
          # allows act to fall back to unauthenticated public fetches
          # when downloading actions from github.com
          token: ${{ github.token || vars.DUMMY_GITHUB_TOKEN }}
          persist-credentials: false

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          app-id: ${{ vars.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
          permission-contents: read
          permission-pull-requests: read

      - name: Add pending change files (only for tests)
        id: add-pending-change-files
        if: env.ACT == 'true' && env.ADD_PENDING_CHANGE_FILES == 'true'
        uses: ./.github/actions/add-pending-change-files
        with:
          branch-name: ${{ github.head_ref }}
          change-file-summary: ${{ vars.CHANGE_FILE_SUMMARY }}

      - name: Check pending change files
        id: check-pending-change-files
        uses: ./.github/actions/check-pending-change-files

      - name: Check feature branch
        id: check-feature-branch
        if: github.head_ref != vars.RELEASE_BRANCH_NAME
        run: |
          if [ "${{ steps.check-pending-change-files.outputs.has-pending-change-files }}" = 'false' ]; then
            echo "No changesets found. Please run 'pnpm changeset add' and push the changes."
            exit 1
          fi

      - name: Check release branch
        id: check-release-branch
        if: github.head_ref == vars.RELEASE_BRANCH_NAME
        run: |
          if [ "${{ steps.check-pending-change-files.outputs.has-pending-change-files }}" = 'true' ]; then
            echo "Found changesets on the release branch. There is something wrong with your workflow"
            exit 1
          fi
