name: PR check

env:
  # errexit - exit immediately if any command fails
  # nounset - error on use of undefined variables
  # pipefail - pipeline fails if any command in it fails, not just the last one
  SHELLOPTS: errexit:nounset:pipefail

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Lint, test, and check changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          client-id: ${{ vars.RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - name: Add mock changeset (ACT)
        if: env.ACT == 'true' && github.head_ref != 'changeset-release/main'
        run: .github/scripts/add-mock-changeset.sh

      - name: Require a changeset for publishable changes
        run: .github/scripts/get-changeset-status.sh
        env:
          HEAD_REF: ${{ github.head_ref }}