name: Release Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  check-for-pending-change-files:
    environment: release
    runs-on: ubuntu-latest
    outputs:
      has-pending-change-files: ${{ steps.check.outputs.has-pending-change-files }}
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          persist-credentials: false

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          install: false

      - id: check
        uses: ./.github/actions/check-for-pending-change-files

      - run: |
          echo ${{ case(
            steps.check.outputs.has-pending-change-files == 'true',
            '::notice::Main branch has pending change files. Ready to proceed to the next step.',
            '::warning::No pending change files found on the main branch. Please run 'pnpm change' and push the generated change files.'
          )}}

  version-bumps-and-changelog-updates:
    needs: check-for-pending-change-files
    if: needs.check-for-pending-change-files.outputs.has-pending-change-files == 'true'
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          persist-credentials: false

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          cache: true
          install: false

      - uses: ./.github/actions/spin-up-virtual-package-registry
        id: registry

      - uses: ./.github/actions/bump-versions-and-update-changelogs
        id: version
        with:
          release-branch-name: ${{ vars.RELEASE_BRANCH_NAME }}
          virtual-registry-server-url: ${{ steps.registry.outputs.registry-server-url }}

      - run: echo ${{ secrets.version.outputs.status }}
